In [1]:
from pathlib import Path

import numpy as np

import roboticstoolbox as rtb
import spatialmath as sm

from manipylator import Robot

[I 03/17/25 03:39:27.942 509] [shell.py:_shell_pop_print@23] Graphical python shell detected, using wrapped sys.stdout


In [2]:
path = Path('/workspace/robots/robot.urdf')
manny = Robot(path)
print(manny.model)

[Genesis] [03:39:31] [INFO] ╭───────────────────────────────────────────────╮
[Genesis] [03:39:31] [INFO] │┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈ Genesis ┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈│
[Genesis] [03:39:31] [INFO] ╰───────────────────────────────────────────────╯
/opt/conda/lib/python3.11/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[Genesis] [03:39:31] [INFO] Running on [Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz] with backend gs.vulkan. Device memory: 15.25 GB.
RHI Error: Can not create Vulkan instance
[W 03/17/25 03:39:31.154 509] [misc.py:adaptive_arch_select@758] Arch=[<Arch.vulkan: 10>] is not supported, falling back to CPU
[Genesis] [03:39:31] [INFO] 🚀 Genesis initialized. 🔖 version: 0.2.1, 🌱 

ERobot: onshape, 5 joints (RRRRR), dynamics, geometry, collision
┌──────┬───────────────────┬───────┬──────────────────┬───────────────────────────────────────────────┐
│ link │       link        │ joint │      parent      │              ETS: parent to link              │
├──────┼───────────────────┼───────┼──────────────────┼───────────────────────────────────────────────┤
│    0 │ base              │       │ BASE             │ SE3()                                         │
│    1 │ carriage_1        │     0 │ base             │ SE3(0, 0, 0.037; -180°, -0°, 0°) ⊕ Rz(q0)     │
│    2 │ shoulder_lift     │     1 │ carriage_1       │ SE3(-0.065, 0, -0.055; 0°, 90°, -0°) ⊕ Rz(q1) │
│    3 │ elbow             │     2 │ shoulder_lift    │ SE3(0.35, 0, 0; -180°, -0°, 0°) ⊕ Rz(q2)      │
│    4 │ wrist_carriage_2  │     3 │ elbow            │ SE3(0.32, 0, -0.025; 180°, -0°, 0°) ⊕ Rz(q3)  │
│    5 │ @wrist_carriage_3 │     4 │ wrist_carriage_2 │ SE3(0.04, 0, -0.0485; 0°, -90°, -0°) ⊕ Rz(q4) │

In [3]:
robot = manny.visualizer.robot
robot

────────────────────── <gs.RigidEntity> ──────────────────────
                'n_qs': <int>: 5
              'n_dofs': <int>: 5
             'n_links': <int>: 6
             'n_geoms': <int>: 10
             'n_cells': <numpy.int64>: 294106
             'n_verts': <int>: 31895
             'n_faces': <int>: 63750
             'n_edges': <int>: 95625
            'n_joints': <int>: 6
            'n_vgeoms': <int>: 10
            'n_vverts': <int>: 124351
            'n_vfaces': <int>: 249250
        'n_equalities': <int>: 0
               'q_end': <int>: 5
             'q_start': <int>: 0
             'is_free': <bool>: True
            'is_built': <bool>: True
             'dof_end': <int>: 5
           'dof_start': <int>: 0
                 'idx': <int>: 1
                 'sim': <gs.Simulator>
                 'uid': <gs.UID>('95fef42-9a7d9401da778dcad22baa388')
           'base_link': <gs.RigidLink>: <3b7211e>, name: 'base', idx: 1
          'base_joint': <gs.RigidJoint>: <6a4e989>,

In [4]:
robot.get_links_pos()

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  3.7000e-02],
        [-6.5000e-02, -6.7356e-18,  9.2000e-02],
        [-6.5000e-02, -4.9598e-17,  4.4200e-01],
        [-4.0000e-02, -8.5725e-17,  7.6200e-01],
        [-8.8500e-02, -4.7547e-17,  8.0200e-01]])

In [5]:
ee = robot.get_link('wrist_carriage_3')
ee

─────────────────── <gs.RigidLink> ───────────────────
          'n_geoms': <int>: 1
          'n_cells': <numpy.int64>: 28800
          'n_verts': <int>: 4422
          'n_faces': <int>: 8840
          'n_edges': <int>: 13260
         'n_vgeoms': <int>: 1
         'n_vverts': <int>: 16606
         'n_vfaces': <int>: 33264
          'is_leaf': <bool>: True
          'is_free': <bool>: True
         'is_built': <bool>: True
              'idx': <int>: 6
        'idx_local': <int>: 5
              'pos': <numpy.ndarray>: array([ 0.04  ,  0.    , -0.0485])
              'uid': <gs.UID>('508e849-f7b374b6f891765c18e69ca57')
         'geom_end': <int>: 11
       'geom_start': <int>: 10
             'name': <str>: 'wrist_carriage_3'
             'quat': <numpy.ndarray>: array([-0.70710678,  0.        ,  0.70710678,  0.        ])
       'child_idxs': <list>: []
 'child_idxs_local': <list>: []
            'geoms': <gs.List>(len=1, [
                         <gs.RigidGeom>: <0a2c31b>, idx: 10 (f

In [6]:
ee_initial_pos = ee.get_pos()
ee_initial_pos

tensor([-8.8500e-02, -4.7547e-17,  8.0200e-01])

In [7]:
ee_initial_quat = ee.get_quat()
ee_initial_quat

tensor([-6.1232e-17,  1.0000e+00, -4.4409e-16,  0.0000e+00])

In [8]:
qpos = robot.inverse_kinematics(
    link = ee,
    pos  = ee_initial_pos,
    quat = ee_initial_quat,
)
qpos

[W 03/17/25 03:39:55.555 509] [frontend_ir.cpp:begin_frontend_struct_for_on_external_tensor@1694] ti.loop_config(serialize=True) does not have effect on the struct for. The execution order is not guaranteed.


tensor([0., 0., 0., 0., 0.])

In [9]:
qpos = robot.inverse_kinematics(
    link = ee,
    pos  = [-4.8500e-02, -4.7547e-02,  4.0200e-01],
    quat = ee_initial_quat,
)
qpos

tensor([-0.8485,  0.9647,  2.3368,  1.3720,  0.8485])

In [10]:
path = robot.plan_path(
    qpos_goal     = qpos,
    num_waypoints = 100, 
    ignore_collision=True,
    ignore_joint_limit=True,
)

[Genesis] [03:39:58] [INFO] Path solution found successfully.


In [11]:
path

[tensor([0., 0., 0., 0., 0.]),
 tensor([-0.0082,  0.0093,  0.0225,  0.0132,  0.0082]),
 tensor([-0.0163,  0.0186,  0.0449,  0.0264,  0.0163]),
 tensor([-0.0245,  0.0278,  0.0674,  0.0396,  0.0245]),
 tensor([-0.0326,  0.0371,  0.0899,  0.0528,  0.0326]),
 tensor([-0.0408,  0.0464,  0.1123,  0.0660,  0.0408]),
 tensor([-0.0490,  0.0557,  0.1348,  0.0792,  0.0490]),
 tensor([-0.0571,  0.0649,  0.1573,  0.0923,  0.0571]),
 tensor([-0.0653,  0.0742,  0.1798,  0.1055,  0.0653]),
 tensor([-0.0734,  0.0835,  0.2022,  0.1187,  0.0734]),
 tensor([-0.0816,  0.0928,  0.2247,  0.1319,  0.0816]),
 tensor([-0.0897,  0.1020,  0.2472,  0.1451,  0.0897]),
 tensor([-0.0979,  0.1113,  0.2696,  0.1583,  0.0979]),
 tensor([-0.1061,  0.1206,  0.2921,  0.1715,  0.1061]),
 tensor([-0.1149,  0.1306,  0.3164,  0.1858,  0.1149]),
 tensor([-0.1237,  0.1407,  0.3408,  0.2001,  0.1237]),
 tensor([-0.1326,  0.1507,  0.3651,  0.2144,  0.1326]),
 tensor([-0.1414,  0.1608,  0.3895,  0.2287,  0.1414]),
 tensor([-0.1503,

In [ ]:
from time import sleep 

for pos in path:
    robot.set_dofs_position(pos)
    manny.visualizer.scene.step()
    sleep(0.1)