In [1]:
from pathlib import Path

import numpy as np

import roboticstoolbox as rtb
import spatialmath as sm

from manipylator import Robot

In [2]:
path = Path('/workspace/robots/robot-ee.urdf')
manny = Robot(path)
print(manny.model)

ERobot: onshape, 6 joints (RRRRRR), dynamics, geometry, collision
┌──────┬──────────────────┬───────┬──────────────────┬────────────────────────────────────────────────┐
│ link │       link       │ joint │      parent      │              ETS: parent to link               │
├──────┼──────────────────┼───────┼──────────────────┼────────────────────────────────────────────────┤
│    0 │ base             │       │ BASE             │ SE3()                                          │
│    1 │ carriage_1       │     0 │ base             │ SE3(0, 0, 0.037; -180°, -0°, 0°) ⊕ Rz(q0)      │
│    2 │ shoulder_lift    │     1 │ carriage_1       │ SE3(-0.065, 0, -0.055; 0°, 90°, -0°) ⊕ Rz(q1)  │
│    3 │ elbow            │     2 │ shoulder_lift    │ SE3(0.35, 0, 0; -180°, -0°, 0°) ⊕ Rz(q2)       │
│    4 │ wrist_carriage_2 │     3 │ elbow            │ SE3(0.32, 0, -0.025; 180°, -0°, 0°) ⊕ Rz(q3)   │
│    5 │ wrist_carriage_3 │     4 │ wrist_carriage_2 │ SE3(0.04, 0, -0.0485; 0°, -90°, -0°) ⊕ Rz(q4)  

In [3]:
manny.model.q

array([0., 0., 0., 0., 0., 0.])

In [29]:
initial_pose = manny.model.fkine(manny.model.q)
initial_pose

   0         0        -1        -0.1285    
   0        -1         0         0         
  -1         0         0         0.8505    
   0         0         0         1         


In [30]:
# q = 0.45
# end_pos = initial_pose
# # Tep = Tep.A
# end_pos.t = [q,q,q]
# end_pos
# # sm_transform = sm.SE3(end_pos)

In [31]:
# initial_pose

In [32]:
manny.model.ik_NR(initial_pose)

(array([0.1, 3.3, 5.5, 3.3, 4.5, 5.4]), 0, 2327, 101, 0.0)

In [25]:
manny.model.ik_NR(manny.model.fkine(manny.model.random_q()))

(array([1.9, 3. , 0.6, 1.6, 4.3, 3.5]), 0, 2186, 101, 0.0)

In [27]:
manny.model.ik_GN(initial_pose)

(array([5.3, 4.5, 4.5, 5.2, 1.2, 3.7]), 0, 2266, 101, 0.0)

In [28]:
manny.model.ik_LM(initial_pose)

(array([1.2, 2. , 3.8, 0.1, 6. , 1.3]), 0, 2239, 101, 0.0)

In [21]:
general_pose = manny.model.fkine([1]*6)
general_pose

  -0.2067   -0.9742    0.09065  -0.3547    
   0.7087   -0.08522   0.7003   -0.09688   
  -0.6745    0.209     0.7081    0.6772    
   0         0         0         1         


In [22]:
manny.model.ik_LM(general_pose)

(array([1., 1., 1., 1., 1., 1.]), 1, 121, 5, 0.0)