In [1]:
from pathlib import Path

import numpy as np

import roboticstoolbox as rtb
import spatialmath as sm

from manipylator import Robot

[I 03/14/25 01:13:50.104 203] [shell.py:_shell_pop_print@23] Graphical python shell detected, using wrapped sys.stdout
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified


In [2]:
path = Path('/workspace/robots/robot-ee.urdf')
manny = Robot(path)
print(manny.model)

[Genesis] [01:15:49] [INFO] ╭───────────────────────────────────────────────╮
[Genesis] [01:15:49] [INFO] │┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈ Genesis ┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈┉┈│
[Genesis] [01:15:49] [INFO] ╰───────────────────────────────────────────────╯
/opt/conda/lib/python3.11/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
[Genesis] [01:15:49] [INFO] Running on [Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz] with backend gs.vulkan. Device memory: 15.25 GB.
RHI Error: Can not create Vulkan instance
[W 03/14/25 01:15:49.455 203] [misc.py:adaptive_arch_select@758] Arch=[<Arch.vulkan: 10>] is not supported, falling back to CPU
[Genesis] [01:15:49] [INFO] 🚀 Genesis initialized. 🔖 version: 0.2.1, 🌱 

ERobot: onshape, 6 joints (RRRRRR), dynamics, geometry, collision
┌──────┬──────────────────┬───────┬──────────────────┬──────────────────────────────────────────────────┐
│ link │       link       │ joint │      parent      │               ETS: parent to link                │
├──────┼──────────────────┼───────┼──────────────────┼──────────────────────────────────────────────────┤
│    0 │ base             │       │ BASE             │ SE3()                                            │
│    1 │ carriage_1       │     0 │ base             │ SE3(0, 0, 0.037; -180°, -0°, 0°) ⊕ Rz(q0)        │
│    2 │ shoulder_lift    │     1 │ carriage_1       │ SE3(-0.065, 0, -0.055; 0°, 90°, -0°) ⊕ Rz(q1)    │
│    3 │ elbow            │     2 │ shoulder_lift    │ SE3(0.35, 0, 0; -180°, -0°, 0°) ⊕ Rz(q2)         │
│    4 │ wrist_carriage_2 │     3 │ elbow            │ SE3(0.32, 0, -0.025; 180°, -0°, 0°) ⊕ Rz(q3)     │
│    5 │ wrist_carriage_3 │     4 │ wrist_carriage_2 │ SE3(0.04, 0, -0.0485; 0°, -90°,

In [3]:
manny.model.q

array([0., 0., 0., 0., 0., 0.])

In [5]:
manny.model.random_q()

array([ 0.41155778, -2.0023637 , -0.31759064, -0.85463239, -1.90612999,
       -1.01328526])

In [4]:
initial_pose = manny.model.fkine(manny.model.q)
initial_pose

   0         0         1        -0.1285    
   1         0         0         0         
   0         1         0         0.8505    
   0         0         0         1         


In [52]:
# q = 0.45
# end_pos = initial_pose
# # Tep = Tep.A
# end_pos.t = [q,q,q]
# end_pos
# # sm_transform = sm.SE3(end_pos)

In [53]:
# initial_pose

In [54]:
manny.model.ik_NR(initial_pose)

(array([5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310]),
 0,
 1,
 101,
 0.0)

In [7]:
manny.model.ik_NR(manny.model.fkine(manny.model.random_q()))

(array([5.15644604e-310, 5.15644604e-310, 5.15644604e-310, 5.15644604e-310,
        5.15644604e-310, 5.15644604e-310]),
 0,
 3100,
 101,
 0.15077800027350877)

In [55]:
manny.model.ik_GN(initial_pose)

(array([5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310]),
 0,
 1,
 101,
 0.0)

In [56]:
manny.model.ik_LM(initial_pose)

(array([5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310]),
 0,
 1,
 101,
 0.0)

In [59]:
general_pose = manny.model.fkine([1]*6)
general_pose

  -0.2175   -0.9719   -0.09065  -0.3547    
  -0.6799    0.2175   -0.7003   -0.09688   
   0.7003   -0.09065  -0.7081    0.6772    
   0         0         0         1         


In [60]:
manny.model.ik_LM(general_pose)

(array([5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310, 5.3e-310]),
 0,
 601,
 101,
 0.0)

In [12]:
%precision 1
manny.model.jacob0(manny.model.q)

array([[ 8.2e-17,  3.9e-31, -5.0e-17, -7.9e-17,  3.6e-17,  0.0e+00],
       [ 1.3e-01, -7.6e-01,  4.1e-01, -8.8e-02,  4.0e-02,  0.0e+00],
       [ 1.6e-17, -1.1e-17, -3.9e-17, -1.1e-17,  4.9e-18,  0.0e+00],
       [ 0.0e+00,  1.0e+00, -1.0e+00,  1.0e+00, -4.2e-15,  1.0e+00],
       [ 1.2e-16,  5.9e-31, -1.2e-16, -8.9e-16,  1.2e-16, -9.5e-16],
       [-1.0e+00, -4.3e-15,  4.3e-15, -4.3e-15, -1.0e+00, -4.3e-15]])

In [ ]:
manny.visualizer.morph.